pipeline:
  build:
    image: node:8
    commands:
      - npm i
      - node index.js

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword