pipeline:
  build:
    image: node:8
    commands:
      - npm i
      - node index.js

  publish:
      image: plugins/docker
      commands:
        - node index.js
      when:
        event: deployment
        environment: staging

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword