pipeline:
  build:
    image: node:8
    commands:
      - npm i

  publish:
      image: plugins/ecr
      repo: test
      region: us-west-1
      registry: 754058048930.dkr.ecr.us-west-1.amazonaws.com
      secrets: [ ecr_access_key, ecr_secret_key ]
      tag:
        - latest
        - on-${DRONE_BUILD_CREATED}
        - job-number-${DRONE_JOB_NUMBER}
        - "commit-${DRONE_COMMIT:0:7}"
#      when:
#        event: deployment
#        environment: staging

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
