pipeline:
  build:
    image: node:8
    commands:
      - npm i
      - node index.js

  publish:
      image: plugins/ecr
      repo: test
      region: us-west-1
      registry: 754058048930.dkr.ecr.us-west-1.amazonaws.com
      secrets: [ ecr_access_key, ecr_secret_key ]
      when:
        event: deployment
        environment: staging

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
