apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-hello-deployment
spec:
  selector:
    matchLabels:
      app: drone-hello
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-hello

    spec:
      containers:
      - name: drone-hello
        image: 754058048930.dkr.ecr.us-west-1.amazonaws.com/test:latest
        ports:
        - containerPort: 80
